### PR TITLE
ql-qlf: k6n10f: Add SDP RAM inference

### PR DESCRIPTION
**Pull request by lpawelcz**
This PR adds the inference of SDP RAM together with synthesis+simulation tests. Test cases use SDP BRAM designs in 4 configurations: 32x512, 16x1024, 8x2048, 4x4096.
Simulation models are the same as for TDP RAM because in both SDP and TDP RAM, yosys internal memory cell is mapped into TDP36 BRAM block but configured in a different way for each RAM type.

### CODE REVIEW

**Comment by rakeshm75** [comment]
I have tested couple designs (32x1024, 8x4096), it works fine. One issue I see is when I use the smaller like 16x1024 & 16x512, it should fit in the 18k block, so split should be set to 1 but I can see that split =0.

**Comment by tpagarani** [comment]
@rakeshm75 right now there is no additional techmap to put 2 18K BRAM together in single TDP_36K.  This will be implemented later. So this PR should be good to merge then.

**Comment by rakeshm75** [comment]
One correction in bram_map.v file:

On line 478 (for CFG_DBITS = 4) the left shift is 5 bits but it should be 2 bits:
		4: begin
			assign A1ADDR_15 = A1ADDR_TOTAL << 5;
			assign B1ADDR_15 = B1ADDR_TOTAL << 5;
its should be:
		4: begin
			assign A1ADDR_15 = A1ADDR_TOTAL << 2;
			assign B1ADDR_15 = B1ADDR_TOTAL << 2;

Similarly on line 111, its:

		4: begin
			assign PORT_A_ADDR = A1EN ? (A1ADDR_TOTAL << 5) : (B1EN ? (B1ADDR_TOTAL << 5) : 15'd0);
			assign PORT_B_ADDR = C1EN ? (C1ADDR_TOTAL << 5) : (D1EN ? (D1ADDR_TOTAL << 5) : 15'd0);

it should be

		4: begin
			assign PORT_A_ADDR = A1EN ? (A1ADDR_TOTAL << 2) : (B1EN ? (B1ADDR_TOTAL << 2) : 15'd0);
			assign PORT_B_ADDR = C1EN ? (C1ADDR_TOTAL << 2) : (D1EN ? (D1ADDR_TOTAL << 2) : 15'd0);

**Comment by lpawelcz** [comment]
@rakeshm75 Thanks for your review! I fixed the shifts for 4 data bits configuration. This should be good to merge now. Please let me know if there is anything else to be fixed or if I can proceed with merging this PR.

**Comment by rakeshm75** [comment]
Yes, its good to merge now.

**Pull request merged**
